
/** generated by createManifest.js **/
module.exports = {
    get: () => {
        return {
          allActions: {
            Router: require('reactium-core/components/Router/actions').default,
            Toolkit: require('reactium-core/components/Toolkit/actions').default,
          },
          allActionTypes: {
            Router: require('reactium-core/components/Router/actionTypes').default,
            Toolkit: require('reactium-core/components/Toolkit/actionTypes').default,
          },
          allReducers: {
            Router: require('reactium-core/components/Router/reducers').default,
            Toolkit: require('reactium-core/components/Toolkit/reducers').default,
          },
          allInitialStates: {
            Router: require('reactium-core/components/Router/state').default,
            Toolkit: require('reactium-core/components/Toolkit/state').default,
          },
          allRoutes: {
            Calculator: require('components/Calculator/route').default,
            Toolkit: require('reactium-core/components/Toolkit/route').default,
          },
          allServices: {
            Toolkit: require('reactium-core/components/Toolkit/services').default,
          },

        }
    },
    list: () => {
        return {
  "allActions": {
    "type": "actions",
    "imports": [
      "reactium-core/components/Router/actions",
      "reactium-core/components/Toolkit/actions"
    ]
  },
  "allActionTypes": {
    "type": "actionTypes",
    "imports": [
      "reactium-core/components/Router/actionTypes",
      "reactium-core/components/Toolkit/actionTypes"
    ]
  },
  "allReducers": {
    "type": "reducers",
    "imports": [
      "reactium-core/components/Router/reducers",
      "reactium-core/components/Toolkit/reducers"
    ]
  },
  "allInitialStates": {
    "type": "state",
    "imports": [
      "reactium-core/components/Router/state",
      "reactium-core/components/Toolkit/state"
    ]
  },
  "allRoutes": {
    "type": "route",
    "imports": [
      "components/Calculator/route",
      "reactium-core/components/Toolkit/route"
    ]
  },
  "allServices": {
    "type": "services",
    "imports": [
      "reactium-core/components/Toolkit/services"
    ]
  }
};
    }
}
